### PR TITLE
Upgraded to .NET 6

### PR DESCRIPTION
**Pull request by ghost**
Folks, I have upgraded the projects to .NET 6. Please review. Thanks.

### CODE REVIEW

**Comment by pereiren** [comment]
> Folks, I have upgraded the projects to .NET 6. Please review. Thanks.

Thank you very much @srihari-tw! I was unable these months to take a look at this. I'll try to check this evening and merge this PR. Best regards friend

**Comment by ghost** [comment]
Thanks buddy!

**Comment by ghost** [comment]
@pereiren I have fixed the dockerfile and tested the same. It was required to be moved a level above in folder hierarchy! Please review.

**Comment by ghost** [comment]
@pereiren Did you get a chance to look at the changes?

**Review by pereiren — APPROVED** [review]

**Comment by pereiren** [comment]
> @pereiren Did you get a chance to look at the changes?

Just now, thank you for collaborating!

**Pull request merged**
